import './header/components/header-lang/header-lang.ts'
import './index/index'
import './header/headerController'
import './header/components/header-navigation/style.ts'
import './header/animation.ts'
