import './header/components/header-lang/header-lang.ts'
import './index/index'
import './header/headerController'
import './header/components/animations/animation.ts'
import '../entities/slider/slider'
