import './header/components/header-lang/header-lang.ts'
import './index/index'
import './header/headerController'
import './slider/slider'
import './header/components/balloon/balloon'
import './header/components/preloader/preloader'
import './header/components/visibility/visibility'
